### ISSUE TITLE
.query() crashes program when given a single query

### ISSUE THREAD

**Issue by jonhoo** [steffengy/tiberius#29] opened 2017-09-01 22:05 UTC
Consider a prepared statement `stmt` consisting of a single `SELECT` query combined with the following code:
```rust
core.run(conn
    .query(&stmt, args)
    .for_each_row(|row| {
	let id: i64 = row.get(0);
	println!("{}", id);
	Ok(())
    }));
```
Currently, that code will crash with something along the lines of
```
thread 'main' panicked at 'stmtstream: unexpected token: Row(TokenRow { meta: TokenColMetaData { columns: [MetaDataColumn { base: BaseMetaDataColumn { flags: (empty), ty: FixedLen(Int8) }, col_name: "id" }] }, columns: [I64(14491)] })', /home/jfrg/.cargo/git/checkouts/tiberius-efcdb30e5dbea5fc/13a096c/tiberius/src/stmt.rs:153:21
```
From my reading of the code, this may have been a recent development with SQL Server deciding to just send the `Row`s directly when there is only one resultset (rather than including a header). Note that switching from `.for_each_row` to iterating over each query set independently with `for_each` and then their rows (like below), encounters the same error. This is further confirmed by the fact that if we add a bogus second query to the prepared statement (i.e., `SELECT ...; SELECT 1`), this code works just fine (it does not if using only a single query):
```rust
let mut done = false;
core.run(conn
    .query(&stmt2, args)
    .for_each(|qs| {
        if done {
    	    drop(qs.wait().collect::<Vec<_>>());
    	    return Ok(());
        }
        done = true;
        let rs: Vec<_> = qs.wait()
    	.map(
    	    |row: Result<tiberius::query::QueryRow, tiberius::TdsError>| -> i64 {
    		let row = row.unwrap();
    		row.get(0)
    	    },
    	)
    	.collect();
        println!("{:?}", rs);
        Ok(())
    }));
```
For what it's worth, I believe this *only* happens with `query` (and not `query_simple`), since only `query` passes through the `StmtStream` which seems to expect a "header" before each run of `Row`s.

**Comment by steffengy** [comment] 2017-09-01 22:16
> From my reading of the code, this may have been a recent development with SQL Server deciding to just send the Rows directly when there is only one resultset (rather than including a header).

That isn't the case as you can see with your output the "header" (or meta data) was received:
`Row(TokenRow { meta: TokenColMetaData { columns: [MetaDataColumn { base: BaseMetaDataColumn { flags: (empty), ty: FixedLen(Int8) }, col_name: "id" }] }, columns: [I64(14491)] })'`

Could you also provide a query & types to reproduce?

**Comment by steffengy** [comment] 2017-09-01 22:17
Also are you testing against master or the crates.io version?

**Comment by jonhoo** [comment] 2017-09-01 22:23
Sorry, maybe I was using the word "header" incorrectly. I end up hitting the panic [here](https://github.com/steffengy/tiberius/blob/master/tiberius/src/stmt.rs#L153), so clearly the stream that `.query`produces expects to get something that is *not* a `TdsResponseToken::Row`, yet that's what it gets. Whereas when I pass two queries to `.query`, that panic is not reached, which suggests that in that case some other kind of `TdsResponseToken` is included before each run of `TdsResponseToken::Row`.

The exact code I'm using is https://github.com/mit-pdos/distributary/blob/master/benchmarks/vote/clients/mssql.rs, though that also ties into a larger benchmarking harness. The database layout is:
```sql
CREATE TABLE art (id bigint PRIMARY KEY NONCLUSTERED, title varchar(16));
CREATE TABLE vt (u bigint, id bigint index vt_article_idx);
CREATE VIEW dbo.awvc WITH SCHEMABINDING AS
    SELECT art.id, art.title, COUNT_BIG(*) AS votes
    FROM dbo.art AS art, dbo.vt AS vt
    WHERE art.id = vt.id
    GROUP BY art.id, art.title;
CREATE UNIQUE CLUSTERED INDEX ix ON dbo.awvc (id);
```
The query is a long string of `SELECT id, title, votes FROM awvc WITH (NOEXPAND) WHERE id = @P{}` joined together with `UNION` (see [here](https://github.com/mit-pdos/distributary/blob/master/benchmarks/vote/clients/mssql.rs#L127)).

I'm testing against the latest commit on master, and this particular problem started with the release of RC2 of SQL Server 2017 (for Linux).

**Comment by jonhoo** [comment] 2017-09-01 22:30
While on the topic of that query, I also run into issues if I string together too many of those `SELECT UNION SELECT` chains in a single query:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Server(TokenError { code: 8016, state: 30, class: 16, message: "The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 3 (\"stmt\"): Data type 0xE7 has an invalid data length or metadata length.", server: "jerry", procedure: "", line: 1 })', /checkout/src/libcore/result.rs:906:4
```
This occurs when executing a prepared statement (i.e., not when preparing it), so I suspect it's either related to passing too many arguments to a prepared statement, or decoding too many returned rows (though there should only be ~100 of them). Is this something you've run into?

**Comment by steffengy** [comment] 2017-09-01 22:33
At what sizes does this second issue occur? Approximately 4096 byte?

**Comment by jonhoo** [comment] 2017-09-01 22:39
Size of what? I think the threshold is at 38 `UNION`'ed `SELECT`s (i.e., 39 breaks), at which point the query is ~2774 characters wide. Each instance of the query should return zero or one row, which consists of two `BIGINT`s and a `TEXT` containing something like "Article #XXXXX" which is ~30 bytes (or 44 with UTF-16) per row (plus any padding), which is ~1672 bytes for 38 rows.

**Comment by steffengy** [comment] 2017-09-01 22:43
Size of the SQL string. The problem might be related to packet size, that should be easier to reproduce.
I'll look into it.

The first issue will take a few more days since I'll first need to upgrade my local SQL server installation (and hope it's reproducable on windows).
If you have a table-independant query for that (e.g. `select 1 union select 2`), that would help alot to verify this actually was introduced by 2017 RC2 [which travis actually runs].

**Comment by jonhoo** [comment] 2017-09-01 22:47
Looking at it again, the breaking point is actually at 56 `SELECT`s, making the query pretty much exactly 4096 characters long. It's a bit curious that the error occurs at the time of query execution, and not when it's prepared though, no?

Ah, I see. I'll try to cook up a simpler reproducing example.

**Comment by steffengy** [comment] 2017-09-01 22:51
Preparing is lazy, since you need to know type information to prepare a query.
So the acutal "preparation" is done on execution, where it checks if the type arguments match
before it uses the prepared statement. If not it needs to (re)prepare.

Then it's pretty certainly an issue with packet size, since currently we do not adhere
to the negotiated packet size when sending packets, which is a problem for big queries.

**Comment by steffengy** [comment] 2017-09-02 00:23
The second issue should be fixed in the latest master.

**Comment by jonhoo** [comment] 2017-09-02 16:28
A much smaller and more self-contained example of this issue:
```rust
// prepare once
let sql = (1..10).map(|_| "SELECT 1").collect::<Vec<_>>().join(" UNION ");
let query = conn.prepare(sql);

// execute twice
for _ in 0..2 {
    let query = conn.query(&query, &[]);
    let future = query.for_each_row(|x| {
        let _: i32 = x.get(0);
        Ok(())
    });
    conn = core.run(future).unwrap();
}
```

**Comment by jonhoo** [comment] 2017-09-04 18:30
@steffengy hey, just wanted to make sure you saw the better test case above.

**Closed** 2017-09-10 11:15 UTC
