### ISSUE TITLE
call stored procedure cause panic!

### ISSUE THREAD

**Issue by gaoqiangz** [steffengy/tiberius#109] opened 2019-11-29 02:54 UTC
```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE p_test
AS
BEGIN
	SET NOCOUNT ON;
END
GO
```

call:
```
conn.simple_exec("EXEC myDB.dbo.p_test")
```

exception:
```
thread 'tokio-runtime-worker-0' panicked at 'resultset: unexpected token: ReturnStatus(0)', C:\Users\pc\.cargo\registry\src\github.com-1ecc6299db9ec823\tiberius-0.3.2\src\query.rs:85:32
```
stored procedure in production environment reports this error :
```
thread 'tokio-runtime-worker-0' panicked at 'resultset: unexpected token: DoneInProc(TokenDone { status: MORE, cur_cmd: 186, done_rows: 0 })', C:\Users\pc\.cargo\registry\src\github.com-1ecc6299db9ec823\tiberius-0.3.2\src\query.rs:85:32
```

**Comment by steffengy** [comment] 2019-11-29 19:54
Duplicate of #108.

**Closed by steffengy** 2019-11-29 19:54 UTC
